import type { MediaJob, SessionCreated, SessionEvent, SessionSnapshot } from "../../integration/dwight/types";
import {
  DEFAULT_ORCHESTRATOR_URL, MAX_IMAGE_BYTES, OrchestratorClient, OrchestratorError, mayProcessMedia,
} from "../../integration/orchestrator-client";
import { isSessionCreated } from "./contracts";

export type ConsentDraft = { personalization: boolean; capture: boolean; enrichment: boolean };
export type Connection = "unpaired" | "connecting" | "active" | "reconnecting" | "offline" | "terminal" | "cancelling" | "cleanup_failed";
export interface KioskState {
  connection: Connection;
  snapshot: SessionSnapshot | null;
  consent: ConsentDraft;
  busy: string | null;
  error: string | null;
  networkError: string | null;
  notice: string | null;
  photoUrl: string | null;
  movieUrl: string | null;
  movieAssetId: string | null;
  uploadedId: string | null;
  photoVersion: number;
  reveal: "unplayed" | "sending" | "acknowledged" | "failed";
  revealError: string | null;
  startAttempted: boolean;
  generation: number;
}

const noConsent = (): ConsentDraft => ({ personalization: false, capture: false, enrichment: false });
const initialState = (): KioskState => ({
  connection: "unpaired", snapshot: null, consent: noConsent(), busy: null, error: null,
  networkError: null, notice: null, photoUrl: null, movieUrl: null, movieAssetId: null,
  uploadedId: null, photoVersion: 0, reveal: "unplayed", revealError: null, startAttempted: false, generation: 0,
});

export class SessionInvalidated extends Error {}

export function acceptSnapshot(
  current: SessionSnapshot | null, incoming: SessionSnapshot, capability: SessionCreated, now = Date.now(),
): SessionSnapshot {
  if (incoming.sessionId !== capability.sessionId) throw new SessionInvalidated("Session mismatch. Rejoin through the trusted bridge.");
  if (incoming.serverInstanceId !== capability.serverInstanceId) throw new SessionInvalidated("The orchestrator restarted. Rejoin through the trusted bridge.");
  if (current && incoming.revision < current.revision) return current;
  if (incoming.expiresAt <= now) throw new SessionInvalidated("This session has expired. Rejoin through the trusted bridge.");
  if (incoming.state === "cancelled") throw new SessionInvalidated("This session was revoked. Local media has been cleared.");
  // Every response contains full domain state, including a cursor reset. Never merge absent assets back in.
  return { ...incoming, events: incoming.events.slice(-100) };
}

export function currentJob(snapshot: SessionSnapshot | null): MediaJob | undefined {
  return snapshot?.jobs.filter(job => job.briefId === snapshot.brief?.id)
    .sort((a, b) => b.createdAt - a.createdAt || b.updatedAt - a.updatedAt)[0];
}

export function provenanceLabel(provenance: NonNullable<MediaJob["result"]>["provenance"]): string {
  return {
    generated: "Generated by media adapter",
    mock_fixture: "Synthetic sample — not the customer",
    prerendered_fallback: "Prerecorded fallback",
  }[provenance];
}

export function parsePreferences(input: string): string[] {
  const preferences = input.split(/\r?\n/).map(value => value.trim()).filter(Boolean);
  if (preferences.length > 20 || preferences.some(value => value.length > 200)) {
    throw new Error("Use up to 20 preferences, each no longer than 200 characters.");
  }
  return preferences;
}

export class BlobSlot {
  url: string | null = null;
  constructor(private readonly urls: Pick<typeof URL, "createObjectURL" | "revokeObjectURL"> = URL) {}
  replace(blob: Blob): string {
    this.clear();
    this.url = this.urls.createObjectURL(blob);
    return this.url;
  }
  clear() {
    if (this.url) this.urls.revokeObjectURL(this.url);
    this.url = null;
  }
}

interface ControllerOptions {
  client?: (base: string) => OrchestratorClient;
  urls?: Pick<typeof URL, "createObjectURL" | "revokeObjectURL">;
  pollIntervalMs?: number;
  retryDelayMs?: number;
  maxRetries?: number;
  uuid?: () => string;
  now?: () => number;
}

export class KioskController {
  private state = initialState();
  private listeners = new Set<() => void>();
  private client: OrchestratorClient | null = null;
  private capability: SessionCreated | null = null;
  private root = new AbortController();
  private media = new AbortController();
  private cleanup: AbortController | null = null;
  private pollTimer: ReturnType<typeof setTimeout> | undefined;
  private expiryTimer: ReturnType<typeof setTimeout> | undefined;
  private retries = 0;
  private selectedFile: Blob | null = null;
  private loadingAssetId: string | null = null;
  private photo: BlobSlot;
  private movie: BlobSlot;
  private starts = new Map<string, { key: string; assetId: string; acknowledged: boolean }>();
  private eventRetries = new Map<string, { fingerprint: string; event: SessionEvent }>();
  private reveals = new Map<string, { event: SessionEvent; played: boolean; pending: boolean; acknowledged: boolean }>();
  private readonly makeClient: (base: string) => OrchestratorClient;
  private readonly uuid: () => string;
  private readonly now: () => number;
  private readonly pollInterval: number;
  private readonly retryDelay: number;
  private readonly maxRetries: number;

  constructor(options: ControllerOptions = {}) {
    this.makeClient = options.client ?? (base => new OrchestratorClient(base));
    this.photo = new BlobSlot(options.urls);
    this.movie = new BlobSlot(options.urls);
    this.uuid = options.uuid ?? (() => crypto.randomUUID());
    this.now = options.now ?? Date.now;
    this.pollInterval = options.pollIntervalMs ?? 1500;
    this.retryDelay = options.retryDelayMs ?? 1000;
    this.maxRetries = options.maxRetries ?? 5;
  }

  getState = () => this.state;
  subscribe = (listener: () => void) => { this.listeners.add(listener); return () => { this.listeners.delete(listener); }; };
  private set(patch: Partial<KioskState>) {
    this.state = { ...this.state, ...patch };
    for (const listener of this.listeners) listener();
  }
  private epoch() { return this.root; }
  private valid(epoch: AbortController) { return this.root === epoch && !epoch.signal.aborted; }
  private stopTimers() {
    clearTimeout(this.pollTimer);
    clearTimeout(this.expiryTimer);
  }

  private clearMedia() {
    this.media.abort();
    this.media = new AbortController();
    this.selectedFile = null;
    this.loadingAssetId = null;
    this.photo.clear();
    this.movie.clear();
    this.set({
      photoUrl: null, movieUrl: null, movieAssetId: null, uploadedId: null,
      photoVersion: this.state.photoVersion + 1, reveal: "unplayed", revealError: null,
    });
  }

  private clearSession() {
    this.stopTimers();
    this.root.abort();
    this.cleanup?.abort();
    this.cleanup = null;
    this.clearMedia();
    this.client?.forget();
    this.client = null;
    this.capability = null;
    this.starts.clear();
    this.eventRetries.clear();
    this.reveals.clear();
    this.root = new AbortController();
    this.retries = 0;
  }

  private terminal(message: string) {
    this.clearSession();
    this.set({ ...initialState(), connection: "terminal", error: message, generation: this.state.generation + 1 });
  }

  private receive(incoming: SessionSnapshot) {
    if (!this.capability) return;
    const before = this.state.snapshot;
    const snapshot = acceptSnapshot(before, incoming, this.capability, this.now());
    if (snapshot === before) return;
    const changedConsent = before?.consent?.consentId !== snapshot.consent?.consentId;
    const changedBrief = before?.brief?.id !== snapshot.brief?.id;
    if (!mayProcessMedia(snapshot, this.now()) || changedBrief || before?.customer?.customerId !== snapshot.customer?.customerId) {
      this.clearMedia();
    }
    const result = currentJob(snapshot)?.status === "ready" ? currentJob(snapshot)?.result : undefined;
    if ((this.state.movieAssetId && this.state.movieAssetId !== result?.assetId) ||
      (this.loadingAssetId && this.loadingAssetId !== result?.assetId)) {
      this.media.abort();
      this.media = new AbortController();
      this.loadingAssetId = null;
      this.movie.clear();
      this.set({ movieUrl: null, movieAssetId: null, reveal: "unplayed", revealError: null });
    }
    const consent = changedConsent ? (snapshot.consent ? {
      personalization: snapshot.consent.personalization, capture: snapshot.consent.capture, enrichment: snapshot.consent.enrichment,
    } : noConsent()) : this.state.consent;
    this.set({
      snapshot, consent, startAttempted: !!snapshot.brief && this.starts.has(snapshot.brief.id),
      ...(incoming.resetRequired ? { notice: "Reconnected to the full session state. Outdated media has been discarded." } : {}),
    });
    clearTimeout(this.expiryTimer);
    this.expiryTimer = setTimeout(() => this.terminal("This session has expired. Rejoin through the trusted bridge."),
      Math.min(Math.max(0, snapshot.expiresAt - this.now()), 2147483647));
  }

  private handleError(error: unknown): string {
    const message = error instanceof Error ? error.message : "The request could not be completed.";
    if (error instanceof SessionInvalidated || (error instanceof OrchestratorError &&
      (error.terminal || error.code === "SESSION_MISMATCH"))) this.terminal(message);
    return message;
  }

  async connect(base: string, input: SessionCreated | string) {
    if (this.state.connection === "cancelling" || this.state.connection === "cleanup_failed") return;
    this.clearSession();
    this.set({ ...initialState(), connection: "connecting", generation: this.state.generation + 1 });
    const epoch = this.epoch();
    try {
      const client = this.makeClient(base || DEFAULT_ORCHESTRATOR_URL);
      this.client = client;
      const capability = typeof input === "string" ? await client.pair(input, epoch.signal) : input;
      if (!this.valid(epoch)) return;
      if (!isSessionCreated(capability)) throw new Error("Check all three fields from the trusted bridge.");
      client.join(capability);
      this.capability = { ...capability };
      await this.poll();
    } catch (error) {
      if (!this.valid(epoch)) return;
      this.terminal(this.handleError(error));
    }
  }

  private async poll() {
    const client = this.client;
    if (!client || !this.capability) return;
    const epoch = this.epoch();
    try {
      const snapshot = await client.snapshot(this.state.snapshot?.revision ?? 0, epoch.signal);
      if (!this.valid(epoch)) return;
      this.receive(snapshot);
      this.retries = 0;
      this.set({ connection: "active", networkError: null });
      this.pollTimer = setTimeout(() => void this.poll(), this.pollInterval);
    } catch (error) {
      if (!this.valid(epoch)) return;
      const message = this.handleError(error);
      if (!this.valid(epoch)) return;
      this.retries++;
      const exhausted = this.retries >= this.maxRetries;
      this.set({
        connection: exhausted ? "offline" : "reconnecting",
        networkError: `${message} ${exhausted ? "Automatic reconnect stopped. Retry when the connection is ready." : `Reconnect ${this.retries} of ${this.maxRetries}.`}`,
      });
      if (!exhausted) this.pollTimer = setTimeout(() => void this.poll(), Math.min(this.retryDelay * 2 ** (this.retries - 1), 10000));
    }
  }

  retryConnection() {
    if (!["offline", "reconnecting"].includes(this.state.connection) || !this.capability) return;
    clearTimeout(this.pollTimer);
    this.retries = 0;
    this.set({ connection: "reconnecting" });
    void this.poll();
  }

  private async refresh(client: OrchestratorClient, epoch: AbortController) {
    const snapshot = await client.snapshot(this.state.snapshot?.revision ?? 0, epoch.signal);
    if (this.valid(epoch)) this.receive(snapshot);
  }

  private async action(label: string, run: (client: OrchestratorClient, epoch: AbortController) => Promise<void>) {
    if (!this.client || this.state.busy || this.state.connection !== "active") return;
    const epoch = this.epoch();
    this.set({ busy: label, error: null, notice: null });
    try {
      await run(this.client, epoch);
    } catch (error) {
      if (this.valid(epoch)) {
        const message = this.handleError(error);
        if (this.valid(epoch)) this.set({ error: message });
      }
    } finally {
      if (this.valid(epoch)) this.set({ busy: null });
    }
  }

  setConsent(key: keyof ConsentDraft, value: boolean) {
    this.set({ consent: { ...this.state.consent, [key]: value } });
    if (!value && key !== "enrichment") this.clearMedia();
  }

  canUseMedia() {
    return mayProcessMedia(this.state.snapshot, this.now()) && this.state.consent.capture && this.state.consent.personalization;
  }

  private retryEvent(type: "consent_recorded" | "context_updated", payload: ConsentDraft | { preferences: string[] }): SessionEvent {
    const fingerprint = JSON.stringify(payload);
    const saved = this.eventRetries.get(type);
    if (saved?.fingerprint === fingerprint) return saved.event;
    const event = { schemaVersion: 1, eventId: this.uuid(), type, payload } as SessionEvent;
    this.eventRetries.set(type, { fingerprint, event });
    return event;
  }

  saveConsent() {
    return this.action("Saving permissions", async (client, epoch) => {
      const event = this.retryEvent("consent_recorded", { ...this.state.consent });
      const snapshot = await client.event(event, epoch.signal);
      if (!this.valid(epoch)) return;
      this.receive(snapshot);
      this.eventRetries.delete("consent_recorded");
      this.set({ notice: "Permissions confirmed by the orchestrator." });
    });
  }

  identify(customerId: "demo-alex" | "demo-sam") {
    return this.action("Selecting customer", async (client, epoch) => {
      if (!this.state.snapshot?.consent?.personalization) throw new Error("Confirm personalization permission first.");
      if (this.state.startAttempted || currentJob(this.state.snapshot)) throw new Error("End this session before changing the customer.");
      const customer = await client.identify(customerId, epoch.signal);
      if (customer.customerId !== customerId) throw new OrchestratorError("Customer receipt did not match.", 0, "INVALID_RESPONSE");
      if (this.valid(epoch)) await this.refresh(client, epoch);
    });
  }

  confirmPreferences(input: string) {
    return this.action("Confirming preferences", async (client, epoch) => {
      if (!this.state.snapshot?.customer || !this.state.snapshot.consent?.personalization) throw new Error("Choose the demo customer after permission is confirmed.");
      if (this.state.startAttempted || currentJob(this.state.snapshot)) throw new Error("End this session before changing a submitted brief.");
      const event = this.retryEvent("context_updated", { preferences: parsePreferences(input) });
      const snapshot = await client.event(event, epoch.signal);
      if (!this.valid(epoch)) return;
      this.receive(snapshot);
      this.eventRetries.delete("context_updated");
      this.set({ notice: "Preferences confirmed. The next brief uses this context revision." });
    });
  }

  createBrief() {
    return this.action("Creating the brief", async (client, epoch) => {
      if (!this.canUseMedia() || !this.state.snapshot?.context || !this.state.snapshot.customer) throw new Error("Confirm permissions, customer and preferences first.");
      if (this.state.startAttempted || currentJob(this.state.snapshot)) throw new Error("A media job already belongs to this brief.");
      await client.createBrief(epoch.signal);
      if (this.valid(epoch)) await this.refresh(client, epoch);
    });
  }

  selectPhoto(file: Blob) {
    if (!this.canUseMedia() || !this.state.snapshot?.brief || this.state.connection !== "active" ||
      this.state.busy || this.state.snapshot.brief.contextRevision !== this.state.snapshot.context?.revision ||
      this.state.startAttempted || currentJob(this.state.snapshot)) return;
    if (!["image/png", "image/jpeg"].includes(file.type) || file.size < 1 || file.size > MAX_IMAGE_BYTES) {
      this.set({ error: "Choose a PNG or JPEG image up to 5 MiB." });
      return;
    }
    this.media.abort();
    this.media = new AbortController();
    this.selectedFile = file;
    this.set({ photoUrl: this.photo.replace(file), uploadedId: null, error: null });
  }

  uploadPhoto() {
    return this.action("Uploading the reference", async (client, epoch) => {
      if (!this.canUseMedia() || !this.selectedFile || !this.state.snapshot?.brief ||
        this.state.snapshot.brief.contextRevision !== this.state.snapshot.context?.revision ||
        this.state.startAttempted || currentJob(this.state.snapshot)) throw new Error("Choose a permitted reference for the current brief first.");
      const media = this.media;
      const upload = await client.uploadImage(this.selectedFile, this.state.snapshot, media.signal);
      if (!this.valid(epoch) || media.signal.aborted) return;
      this.selectedFile = null;
      this.set({ uploadedId: upload.assetId, notice: "Reference uploaded to this session. Review the brief, then create the movie." });
    });
  }

  startMedia() {
    return this.action("Starting the movie", async (client, epoch) => {
      const brief = this.state.snapshot?.brief;
      if (!brief || !this.canUseMedia() || !this.state.uploadedId ||
        brief.contextRevision !== this.state.snapshot?.context?.revision) throw new Error("Create a current brief and upload its permitted reference first.");
      if (currentJob(this.state.snapshot)) throw new Error("This brief already has a media job. Follow its status below.");
      let attempt = this.starts.get(brief.id);
      if (!attempt) {
        attempt = { key: this.uuid(), assetId: this.state.uploadedId, acknowledged: false };
        this.starts.set(brief.id, attempt);
      }
      if (attempt.assetId !== this.state.uploadedId) throw new Error("The reference changed. Do not retry this command with another image.");
      this.set({ startAttempted: true });
      await client.startMedia(brief.id, attempt.key, epoch.signal);
      if (!this.valid(epoch)) return;
      attempt.acknowledged = true;
      this.set({ notice: "Movie request accepted. Progress below is reported by the orchestrator." });
      await this.refresh(client, epoch);
    });
  }

  loadMovie() {
    return this.action("Verifying the movie", async (client, epoch) => {
      const job = currentJob(this.state.snapshot);
      if (!this.canUseMedia() || job?.status !== "ready" || !job.result) throw new Error("No authorized ready movie is available.");
      if (this.state.movieAssetId === job.result.assetId) return;
      const media = this.media;
      this.loadingAssetId = job.result.assetId;
      try {
        const blob = await client.downloadMovie(job.result, media.signal);
        const current = currentJob(this.state.snapshot);
        if (!this.valid(epoch) || media.signal.aborted || !this.canUseMedia() ||
          current?.status !== "ready" || current.result?.assetId !== job.result.assetId) return;
        this.set({ movieUrl: this.movie.replace(blob), movieAssetId: job.result.assetId, reveal: "unplayed", revealError: null });
      } finally {
        if (this.loadingAssetId === job.result.assetId) this.loadingAssetId = null;
      }
    });
  }

  onPlaying() {
    const job = currentJob(this.state.snapshot);
    if (!this.canUseMedia() || !this.state.movieUrl || !job?.result ||
      job.result.assetId !== this.state.movieAssetId || job.status !== "ready") return;
    let reveal = this.reveals.get(job.jobId);
    if (!reveal) {
      reveal = { event: { schemaVersion: 1, eventId: this.uuid(), type: "media_revealed", payload: { jobId: job.jobId } },
        played: true, pending: false, acknowledged: false };
      this.reveals.set(job.jobId, reveal);
      if (this.state.connection === "active") void this.sendReveal(job.jobId);
      else this.set({ reveal: "failed", revealError: "Playback occurred while disconnected. Reconnect, then retry the playback acknowledgement." });
    }
  }

  retryReveal() {
    const job = currentJob(this.state.snapshot);
    if (job) return this.sendReveal(job.jobId);
  }

  private async sendReveal(jobId: string) {
    const reveal = this.reveals.get(jobId);
    const client = this.client;
    if (!client || !reveal?.played || reveal.pending || reveal.acknowledged || !this.canUseMedia() ||
      this.state.connection !== "active" || !this.state.movieUrl) return;
    const epoch = this.epoch();
    reveal.pending = true;
    this.set({ reveal: "sending", revealError: null });
    try {
      const snapshot = await client.event(reveal.event, epoch.signal);
      if (!this.valid(epoch)) return;
      this.receive(snapshot);
      reveal.acknowledged = true;
      this.set({ reveal: "acknowledged" });
    } catch (error) {
      if (!this.valid(epoch)) return;
      const message = this.handleError(error);
      if (this.valid(epoch)) this.set({ reveal: "failed", revealError: `${message} Playback occurred, but its acknowledgement is unconfirmed.` });
    } finally { reveal.pending = false; }
  }

  playbackError() {
    this.set({ error: "This browser could not play the verified MP4. No new reveal acknowledgement was sent. Try another supported browser." });
  }

  async cancel() {
    if (!this.client || !this.capability || this.state.connection === "cancelling") return;
    const client = this.client;
    this.stopTimers();
    this.root.abort();
    this.clearMedia();
    this.starts.clear();
    this.eventRetries.clear();
    this.reveals.clear();
    // DELETE owns a fresh bounded signal; the polling/render signal has already been aborted.
    this.cleanup = new AbortController();
    const cleanup = this.cleanup;
    this.set({
      connection: "cancelling", snapshot: null, consent: noConsent(), busy: null,
      error: null, networkError: null, notice: "Local capture and playback stopped. Requesting server cleanup…",
      startAttempted: false, generation: this.state.generation + 1,
    });
    try {
      await client.revoke(cleanup.signal);
      if (cleanup.signal.aborted) return;
      this.clearSession();
      this.set({ ...initialState(), notice: "Session ended. The orchestrator confirmed cleanup.", generation: this.state.generation + 1 });
    } catch (error) {
      if (cleanup.signal.aborted) return;
      const message = error instanceof Error ? error.message : "Cleanup request failed.";
      if (error instanceof OrchestratorError && error.terminal) {
        this.terminal(`${message} Access ended; server cleanup could not be confirmed. Ask the operator to reconcile cleanup.`);
      } else {
        this.set({
          connection: "cleanup_failed", notice: null,
          error: `${message} Local media is cleared, but server cleanup is NOT confirmed. Retry cleanup before pairing another customer.`,
        });
      }
    }
  }

  dispose() {
    this.clearSession();
    this.state = initialState();
    this.listeners.clear();
  }
}
